export const MINT_TOKEN = 'MINT_TOKEN';
export const WITHDRAW_TOKEN = 'WITHDRAW_TOKEN';
export const BORROW_TOKEN = 'BORROW_TOKEN';
export const REPAY_BORROW_TOKEN = 'REPAY_BORROW_TOKEN';
export const COLLATERALIZE_TOKEN = 'COLLATERALIZE_TOKEN';
export const DISABLE_COLLATERALIZE_TOKEN = 'DISABLE_COLLATERALIZE_TOKEN';
