export const GET_SUPPLY_MARKET_MODAL_DATA = 'GET_SUPPLY_MARKET_MODAL_DATA';
export const GET_BORROW_MARKET_MODAL_DATA = 'GET_BORROW_MARKET_MODAL_DATA';

export const MINT_TOKEN = 'MINT_TOKEN';
export const WITHDRAW_TOKEN = 'WITHDRAW_TOKEN';
export const BORROW_TOKEN = 'BORROW_TOKEN';
export const REPAY_BORROW_TOKEN = 'REPAY_BORROW_TOKEN';
