name: Build

on:
  pull_request:
    branches: ['*']

jobs:
  build_and_test_smart_contracts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: actions/setup-python@v2
      - name: "Install SmartPy"
        run: |
          bash <(curl -s https://legacy.smartpy.io/cli/install.sh) --yes
      - name: "Version Check"
        run: |
          ~/smartpy-cli/SmartPy.sh --version
      - name: "Run tests"
        run: |
          bash contracts/tests/run_tests.sh ~/smartpy-cli/SmartPy.sh

  build_and_test_typescript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: "Build and test utility package"
        working-directory: src/util
        run: |
          npm ci
          npm run build
          npm test
      - name: "Build React UI"
        working-directory: src/ui
        run: |
          npm ci
          DISABLE_ESLINT_PLUGIN=true npm run build
      - name: "Build post-deployment package"
        working-directory: postdeploy
        run: |
          npm ci
          npm run build
